accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp' # 라우팅 편리하게 하기 위해서 작성해둔 것
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'
urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'
urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
    ]

project2/urls.py
from django.conf import settings
from django.conf.global_settings import MEDIA_URL
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)

    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                               related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)
    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld

# url에서 마지막에 숫자가 계정을 의미하는데. 그러니까 그 숫자만 바꾸면 다른 계정으로 접근 가능. 이거를 막자!!
from articleapp.models import Article



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accountapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list,
                                        **kwargs)


has_ownership = [login_required, account_ownership_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'
    
    # def get(self, request, *args, **kwargs):
    #     # and : 이 user가 해당 페이지 주인이 맞는지 확인. self.get_object() self는 저 view 자체를 의미 -> target user를 가져오기
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         return super().get(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    #     def post(self, request, *args, **kwargs):
    #         if request.user.is_authenticated and self.get_object() == request.user:
    #             return super().post(request, *args, **kwargs)  # 부모 메소드에서 pos 불러오기
    #         else:
    #             return HttpResponseForbidden()

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Sign up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method='post'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class='m-5'>
                    <input type='submit' class='btn btn-dark rounded-pill px-5'>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}}
{% block content %}
<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Quit</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method='post'>
            {% csrf_token %}
            <div class='m-5'>
                <input type='submit' class='btn btn-dark rounded-pill px-5'>
            </div>
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{#create.html 복사#}

{% extends 'base.html' %}
{#base.html 안에 있는 block content 부분만 수정하겠다.#}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
{#            닉네임있으면 닉네임 출력. 없으면 프로필 만드는 페이지로 연결#}
            {% if target_user.profile %}
{#                이미지도 출력#}
                <img src="{{ target_user.profile.image.url }}"
                     class='profile_image m-4'
                     alt="profile image">

                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                        class="material-icons round_button">
                        edit
                    </a>
                    {% endif %}

                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h4>
                <a href="{% url 'profileapp:create' %}">
                    Create Profile
                </a>
            </h4>
            {% endif %}
        </div>

{#    디테일 페이지의 url을 복사해서 로그아웃한 상태에서 검색해보니까 나온다 이거야!! 그러면 안 되지.#}
{#        프로필 주인과 요청 보내고 있는 user와 같으면 보여주기(요청 보내고 잇는 user와 우리 데베에ㅓ 저장돼있는 target user 랑 같다면 보여줘라#}
        {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
                class="material-icons round_button mx-1">
                settings
            </a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
                class="material-icons round_button mx-1">
                close
            </a>
        </div>
        {% endif %}
    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{#base.html 안에 있는 block content 부분만 수정하겠다.#}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
{#            action : 요청을 보낼 주소. 원래 / 를 썼었는데 우리는 name을 정해놨기 때문에 그걸 사용. reverse 말고 url씀#}
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
{#                만들어준 class 에서 만든 form을 단순 출력#}
                {% bootstrap_form form %}
                <div class="m-5">
                    {#                트리거 , px-5 : padding x 축 5 #}
                    <input type="submit" class='btn btn-dark rounded-pill px-5'>
                </div>


            </form>
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}}
{% load bootstrap4 %}
{% block content %}
<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Update info</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class='m-5'>
                <input type='submit' class='btn btn-dark rounded-pill px-5'>
            </div>
        </form>
    </div>
</div>

{% endblock %}